name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
            gcc-aarch64-linux-gnu \
            make \
            build-essential
      - name: Run unit test
        run: ./unit-test.sh

  full-test:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
            gcc-aarch64-linux-gnu \
            make \
            build-essential \
            qemu-system-arm \
            qemu-efi \
            libncurses-dev \
            bc \
            bison \
            flex \
            libssl-dev
      - name: Run full test
        run: ./full-test.sh

