name: assignment-test
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  unit-test:
    container: cuaesd/aesd-autotest:24-unit-test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run unit test
        run: ./unit-test.sh

  full-test:
    container: cuaesd/aesd-autotest:24-assignment3
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu make build-essential qemu-system-arm qemu-efi-aarch64 libncurses-dev bc bison flex libssl-dev
      - name: Run full test
        run: ./full-test.sh
